apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: prod
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: test-web-app